# .github/workflows/version-check.yml

name: Ensure version.txt was updated

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # so we can compare with previous commit

      - name: Check if version.txt was modified
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^src/version\.txt$'; then
            echo "✅ version.txt was updated."
          else
            echo "❌ version.txt was NOT updated."
            echo "You must bump the version for OTA clients."
            exit 1

